DROP DATABASE sahara;
create database sahara;
USE sahara;
CREATE TABLE USER(
    ID int NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(255) NOT NULL, 
    PRIMARY KEY (ID)
);

CREATE TABLE NOTIFICATION_ACCOUNT(
    ID int NOT NULL AUTO_INCREMENT,
    ACCOUNT varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY(
    ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    TITLE varchar(255),
    COLOR varchar(255),
    DISCRIPTION varchar(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE EVENTS(
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    DISCRIPTION varchar(255),
    START_TIME DATETIME,
    END_TIME DATETIME,
    PRIMARY KEY (ID)

);

CREATE TABLE CLASS_EVENT(
    ID int NOT NULL AUTO_INCREMENT,
    CATEGORY_ID int NOT NUll,
    EVENT_ID int NOT NULL,
    USER_ROLL varchar(255),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE TASK(
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    DISCRIPTION varchar(255),
    START_TIME DATETIME,
    END_TIME DATETIME,
    PRIMARY KEY (ID)
);