DROP DATABASE sahara;
create database sahara;
USE sahara;
CREATE TABLE USER(
    ID int NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(255) NOT NULL, 
    PRIMARY KEY (ID)
);

INSERT INTO USER (EMAIL,PASSWORD,ROLE) VALUES ('kyler','kyler','user');

CREATE TABLE NOTIFICATION_ACCOUNT(
    ID int NOT NULL AUTO_INCREMENT,
    ACCOUNT varchar(255),
    PRIMARY KEY (ID)
);

insert into CATEGORY (USER_ID,TITLE,COLOR,DISCRIPTION) VALUES (1,'this is a test category','blue','this is a test category for the user kyler.daybell96@gmail.com');

CREATE TABLE CATEGORY(
    ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    TITLE varchar(255),
    COLOR varchar(255),
    DISCRIPTION varchar(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    PRIMARY KEY (ID)
);
insert into EVENTS (TITLE,DISCRIPTION,CATEGORY_ID,START_TIME,END_TIME) VALUES 
('GO RUNNING','go for a quick jog arround the block',1,NOW(),NOW()+10);
CREATE TABLE EVENTS(
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    DISCRIPTION varchar(255),
    CATEGORY_ID int NOT NULL,
    START_TIME DATETIME,
    END_TIME DATETIME,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    PRIMARY KEY (ID)

);

CREATE TABLE TASK(
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    DISCRIPTION varchar(255),
    START_TIME DATETIME,
    END_TIME DATETIME,
    PRIMARY KEY (ID)
);